name: hotel-management
region: sgp

services:
- name: web
  github:
    repo: TomVietCode/hotel-management
    branch: main
    deploy_on_push: true
  
  build_command: |
    composer install --no-dev --optimize-autoloader --no-interaction
    npm ci
    npm run build
    php artisan storage:link
  
  run_command: |
    php artisan config:cache
    php artisan migrate --force
    vendor/bin/heroku-php-apache2 public/
  
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  
  http_port: 8080
  
  routes:
  - path: /
  
  envs:
  - key: APP_NAME
    value: "Novotel"
  - key: APP_ENV
    value: "production"
  - key: APP_DEBUG
    value: "false"
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: APP_URL
    value: "https://novotel-f9rcy.ondigitalocean.app"
    scope: RUN_AND_BUILD_TIME
  - key: FORCE_HTTPS
    value: "true"
  - key: DB_CONNECTION
    value: "mysql"
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
  - key: DB_DATABASE
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_USERNAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SESSION_DRIVER
    value: "database"
  - key: CACHE_STORE
    value: "database"
  - key: QUEUE_CONNECTION
    value: "database"