# Cấu hình tạm thời - CHỈ ĐỂ XÁC THỰC
server {
    listen 80;
    server_name novotel.cuongdev.tech www.novotel.cuongdev.tech;

    # Đây là phần cho Certbot xác thực
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Chuyển hướng các request khác (tạm thời)
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
  listen 443 ssl http2;
  server_name novotel.cuongdev.tech www.novotel.cuongdev.tech;
  root /var/www/html/public;

  ssl_certificate /etc/letsencrypt/live/novotel.cuongdev.tech/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/novotel.cuongdev.tech/privkey.pem;

  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-Content-Type-Options "nosniff";

  index index.php
  charset utf-8;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  error_page 404 /index.php;

  location ~ \.php$ {
    fastcgi_pass app:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    include fastcgi_params;
  }

  location ~ /\.(?!well-known).* {
    deny all;
  }
}